project:
  type: book
  resources:
    - CNAME               # Added to ensure your domain file is kept during rendering

book:
  title: "AI for Eco-Innovations"
  author: "Han-Teng Liao"
  date: "23/07/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

babelquarto:
  languagecodes:
  - name: ja
    text: "日本語"
  - name: zh-TW
    text: "正體中文"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['ja', 'zh-TW']
  title-ja: "エコイノベーションのためのAI"
  title-zh-TW: "人工智慧促進生態創新"
  description-ja: ""
  description-zh-TW: ""
  abstract-ja: ""
  abstract-zh-TW: ""
  author-ja: ""
  author-zh-TW: ""
  lang: en

